server:
  port: 9527

# 日志配置
logging:
  file:
    path: "logs/"
    name: "application-%d{yyyy/MM/dd-HH:mm:ss}.log"
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n "
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"