server:
  port: 9527

# 日志配置
logging:
  file:
    name: "logs/application.log"
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n "
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"

# 服务设置
zone:
  motionless:
    # 爬虫设置
    crawler:
      tmsfw:
        # 站点域名
        domain: "www.tmsf.com"
        # 透明售房网首页
        index-url: "http://www.tmsf.com"
        # 新房首页
        new-house-url: "http://www.tmsf.com/newhouse/property_searchall.htm"
        # 抓取5000条预售证数据
        pre-sale-count: 5000
    # 位置服务设置
    location:
      # 高德API
      gaode:
        # key
        key: "db1d8f34837843dc552d2a1340e94d92"
        # 域名
        domain: "https://restapi.amap.com"
        # 地理编码API
        geo-api: "/v3/geocode/geo?city=%s&address=%s&key=%s"


# mysql 设置
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/house_analyze?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&nullCatalogMeansCurrent=true"
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis设置
mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath:mapper/**/*.xml
  type-aliases-package: zone.motionless.houseanalyzer.model
  not-empty: true
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
