package zone.motionless.houseanalyzer.model;

import java.io.Serializable;
import java.util.Date;

public class CrawlerConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_config.id
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_config.domain
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_config.cookie
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    private String cookie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_config.created_at
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_config.updated_at
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crawler_config
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_config.id
     *
     * @return the value of crawler_config.id
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_config.id
     *
     * @param id the value for crawler_config.id
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_config.domain
     *
     * @return the value of crawler_config.domain
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_config.domain
     *
     * @param domain the value for crawler_config.domain
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_config.cookie
     *
     * @return the value of crawler_config.cookie
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    public String getCookie() {
        return cookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_config.cookie
     *
     * @param cookie the value for crawler_config.cookie
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    public void setCookie(String cookie) {
        this.cookie = cookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_config.created_at
     *
     * @return the value of crawler_config.created_at
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_config.created_at
     *
     * @param createdAt the value for crawler_config.created_at
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_config.updated_at
     *
     * @return the value of crawler_config.updated_at
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_config.updated_at
     *
     * @param updatedAt the value for crawler_config.updated_at
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}