package zone.motionless.houseanalyzer.model;

import java.util.Date;

public class LouPan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.id
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.name
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.created_at
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.updated_at
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.status
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.id
     *
     * @return the value of loupan.id
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.id
     *
     * @param id the value for loupan.id
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.name
     *
     * @return the value of loupan.name
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.name
     *
     * @param name the value for loupan.name
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.created_at
     *
     * @return the value of loupan.created_at
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.created_at
     *
     * @param createdAt the value for loupan.created_at
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.updated_at
     *
     * @return the value of loupan.updated_at
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.updated_at
     *
     * @param updatedAt the value for loupan.updated_at
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.status
     *
     * @return the value of loupan.status
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.status
     *
     * @param status the value for loupan.status
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}