package zone.motionless.houseanalyzer.model;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class LouPan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.id
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.name
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.type
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.left_count
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private Integer leftCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.count
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.address
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.current_sale_price
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private Integer currentSalePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.telephone
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.status
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.latitude
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private BigDecimal latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.longitude
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private BigDecimal longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.created_at
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loupan.updated_at
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.id
     *
     * @return the value of loupan.id
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.id
     *
     * @param id the value for loupan.id
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.name
     *
     * @return the value of loupan.name
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.name
     *
     * @param name the value for loupan.name
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.type
     *
     * @return the value of loupan.type
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.type
     *
     * @param type the value for loupan.type
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.left_count
     *
     * @return the value of loupan.left_count
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public Integer getLeftCount() {
        return leftCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.left_count
     *
     * @param leftCount the value for loupan.left_count
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setLeftCount(Integer leftCount) {
        this.leftCount = leftCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.count
     *
     * @return the value of loupan.count
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.count
     *
     * @param count the value for loupan.count
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.address
     *
     * @return the value of loupan.address
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.address
     *
     * @param address the value for loupan.address
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.current_sale_price
     *
     * @return the value of loupan.current_sale_price
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public Integer getCurrentSalePrice() {
        return currentSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.current_sale_price
     *
     * @param currentSalePrice the value for loupan.current_sale_price
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setCurrentSalePrice(Integer currentSalePrice) {
        this.currentSalePrice = currentSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.telephone
     *
     * @return the value of loupan.telephone
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.telephone
     *
     * @param telephone the value for loupan.telephone
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.status
     *
     * @return the value of loupan.status
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.status
     *
     * @param status the value for loupan.status
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.latitude
     *
     * @return the value of loupan.latitude
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.latitude
     *
     * @param latitude the value for loupan.latitude
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.longitude
     *
     * @return the value of loupan.longitude
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.longitude
     *
     * @param longitude the value for loupan.longitude
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.created_at
     *
     * @return the value of loupan.created_at
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.created_at
     *
     * @param createdAt the value for loupan.created_at
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loupan.updated_at
     *
     * @return the value of loupan.updated_at
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loupan.updated_at
     *
     * @param updatedAt the value for loupan.updated_at
     *
     * @mbg.generated Wed Oct 06 23:02:04 CST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}