package zone.motionless.houseanalyzer.model;

import java.math.BigDecimal;
import java.util.Date;

public class PreSaleInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.id
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.loupan_id
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Long loupanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.name
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.licence
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private String licence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.house_price_link
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private String housePriceLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.count
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.left_count
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Integer leftCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.developer_company
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private String developerCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.open_date
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Date openDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.type
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.address
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.sale_address
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private String saleAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.latitude
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private BigDecimal latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.longitude
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private BigDecimal longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.avg_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Integer avgPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.min_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Integer minPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.max_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Integer maxPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.created_at
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.updated_at
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_sale_info.status
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.id
     *
     * @return the value of pre_sale_info.id
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.id
     *
     * @param id the value for pre_sale_info.id
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.loupan_id
     *
     * @return the value of pre_sale_info.loupan_id
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Long getLoupanId() {
        return loupanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.loupan_id
     *
     * @param loupanId the value for pre_sale_info.loupan_id
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setLoupanId(Long loupanId) {
        this.loupanId = loupanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.name
     *
     * @return the value of pre_sale_info.name
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.name
     *
     * @param name the value for pre_sale_info.name
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.licence
     *
     * @return the value of pre_sale_info.licence
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public String getLicence() {
        return licence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.licence
     *
     * @param licence the value for pre_sale_info.licence
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setLicence(String licence) {
        this.licence = licence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.house_price_link
     *
     * @return the value of pre_sale_info.house_price_link
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public String getHousePriceLink() {
        return housePriceLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.house_price_link
     *
     * @param housePriceLink the value for pre_sale_info.house_price_link
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setHousePriceLink(String housePriceLink) {
        this.housePriceLink = housePriceLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.count
     *
     * @return the value of pre_sale_info.count
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.count
     *
     * @param count the value for pre_sale_info.count
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.left_count
     *
     * @return the value of pre_sale_info.left_count
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Integer getLeftCount() {
        return leftCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.left_count
     *
     * @param leftCount the value for pre_sale_info.left_count
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setLeftCount(Integer leftCount) {
        this.leftCount = leftCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.developer_company
     *
     * @return the value of pre_sale_info.developer_company
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public String getDeveloperCompany() {
        return developerCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.developer_company
     *
     * @param developerCompany the value for pre_sale_info.developer_company
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setDeveloperCompany(String developerCompany) {
        this.developerCompany = developerCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.open_date
     *
     * @return the value of pre_sale_info.open_date
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Date getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.open_date
     *
     * @param openDate the value for pre_sale_info.open_date
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.type
     *
     * @return the value of pre_sale_info.type
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.type
     *
     * @param type the value for pre_sale_info.type
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.address
     *
     * @return the value of pre_sale_info.address
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.address
     *
     * @param address the value for pre_sale_info.address
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.sale_address
     *
     * @return the value of pre_sale_info.sale_address
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public String getSaleAddress() {
        return saleAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.sale_address
     *
     * @param saleAddress the value for pre_sale_info.sale_address
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setSaleAddress(String saleAddress) {
        this.saleAddress = saleAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.latitude
     *
     * @return the value of pre_sale_info.latitude
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.latitude
     *
     * @param latitude the value for pre_sale_info.latitude
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.longitude
     *
     * @return the value of pre_sale_info.longitude
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.longitude
     *
     * @param longitude the value for pre_sale_info.longitude
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.avg_price
     *
     * @return the value of pre_sale_info.avg_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Integer getAvgPrice() {
        return avgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.avg_price
     *
     * @param avgPrice the value for pre_sale_info.avg_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setAvgPrice(Integer avgPrice) {
        this.avgPrice = avgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.min_price
     *
     * @return the value of pre_sale_info.min_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Integer getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.min_price
     *
     * @param minPrice the value for pre_sale_info.min_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setMinPrice(Integer minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.max_price
     *
     * @return the value of pre_sale_info.max_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Integer getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.max_price
     *
     * @param maxPrice the value for pre_sale_info.max_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setMaxPrice(Integer maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.created_at
     *
     * @return the value of pre_sale_info.created_at
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.created_at
     *
     * @param createdAt the value for pre_sale_info.created_at
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.updated_at
     *
     * @return the value of pre_sale_info.updated_at
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.updated_at
     *
     * @param updatedAt the value for pre_sale_info.updated_at
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_sale_info.status
     *
     * @return the value of pre_sale_info.status
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_sale_info.status
     *
     * @param status the value for pre_sale_info.status
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}