package zone.motionless.houseanalyzer.mapper;

import java.util.List;

import org.springframework.stereotype.Component;
import zone.motionless.houseanalyzer.model.CrawlerConfig;

public interface CrawlerConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_config
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_config
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    int insert(CrawlerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_config
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    CrawlerConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_config
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    List<CrawlerConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_config
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    int updateByPrimaryKey(CrawlerConfig record);

    /**
     * 根据站点获取cookie信息
     * @param domain
     * @return
     */
    String selectCookieByDomain(String domain);
}