package zone.motionless.houseanalyzer.mapper;

import zone.motionless.houseanalyzer.model.CrawlerConfig;

public interface CrawlerConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_config
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_config
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    int insert(CrawlerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_config
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    int insertSelective(CrawlerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_config
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    CrawlerConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_config
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    int updateByPrimaryKeySelective(CrawlerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_config
     *
     * @mbg.generated Tue Oct 12 15:15:06 CST 2021
     */
    int updateByPrimaryKey(CrawlerConfig record);
}