package zone.motionless.houseanalyzer.mapper;

import java.util.List;
import zone.motionless.houseanalyzer.model.HousePrice;

public interface HousePriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    int insert(HousePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    HousePrice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    List<HousePrice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_price
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    int updateByPrimaryKey(HousePrice record);
}