package zone.motionless.houseanalyzer.mapper;

import java.util.List;
import zone.motionless.houseanalyzer.model.LouPan;

public interface LouPanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loupan
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loupan
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    int insert(LouPan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loupan
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    LouPan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loupan
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    List<LouPan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loupan
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    int updateByPrimaryKey(LouPan record);
}