package zone.motionless.houseanalyzer.mapper;

import java.util.List;
import zone.motionless.houseanalyzer.model.PreSaleInfo;

public interface PreSaleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_sale_info
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_sale_info
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    int insert(PreSaleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_sale_info
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    PreSaleInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_sale_info
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    List<PreSaleInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_sale_info
     *
     * @mbg.generated Wed Oct 06 19:59:29 CST 2021
     */
    int updateByPrimaryKey(PreSaleInfo record);
}